{{- if or (not .Values.existingSecret) (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  labels:
{{ include "photoprism.labels" . | indent 4 }}
stringData:
{{- if not .Values.database.existingSecret }}
  PHOTOPRISM_DATABASE_DSN: {{ include "photoprism.databaseDSN" . }}
{{- end }}

{{- if not .Values.existingSecret }}
  PHOTOPRISM_ADMIN_PASSWORD: {{ .Values.adminPassword | default "photoprism" | quote }}
{{- end }}

{{- end }}
